# Gems
gems:
  - jekyll-paginate

plugins: [jekyll-paginate]

# Setup
title:        CampusAI
tagline:      Get inspired by latest RL research
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       CampusAI
  url:        https://campusai.github.io/


#Others
markdown: kramdown

include: ['_papers', '_ds', '_ml', '_rl', '_experiments', '_comments']

# Collections
collections:
        - papers
        - projects
        - lectures
        - experiments
        - comments

defaults:
        - scope:
                path: "assets/images/"
          values:
                image: true

# Google analytics
google_analytics: UA-160601102-1
