# Gems
gems:
  - jekyll-paginate

# Setup
title:        CampusAI
tagline:      Review and implementation of interesting AI papers
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       CampusAI
  url:        http://yourhomepage.com 


#Others
markdown: kramdown