# Gems
gems:
  - jekyll-paginate

# Setup
title:        CampusAI
tagline:      Get Inspired by latest RL Research.
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       CampusAI
  url:        https://campusai.github.io/


#Others
markdown: kramdown

include: ['_papers', '_lectures']

# Collections
collections:
        - papers
        - projects
        - lectures

defaults:
        - scope:
                path: "assets/images/"
          values:
                image: true

# Google analytics
google_analytics: UA-160601102-1